//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AIMemory
{
	public static class AIDebug
	{
		public static bool enable_gen_log = true;
		public static bool enable_match_log = true;
		public static bool enable_play_log = false;
	
		public static void GenLog(string log){
			if (enable_gen_log)
				Debug.Log(log);
		}
		
		public static void MatchLog(string log){
			if (enable_match_log)
				Debug.Log(log);
		}
		
		public static void PlayLog(string log){
			if (enable_play_log)
				Debug.Log(log);
		}
		
		public static void Warning(string log){
				Debug.LogWarning(log);
		}
	}
}

