//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AIMemory
{
	public class AIPick
	{
		private int[] indexes = new int[2];
		
		public AIPick ()
		{
			indexes[0] = -1;
			indexes[1] = -1;
		}
		
		public AIPick (int i, int j)
		{
			indexes[0] = i;
			indexes[1] = j;
		}
		
		public int Index(int i){
			if (i < 2){
				return indexes[i];
			}
			AIDebug.Warning("AIPick index out of range");
			return -1;
		}
		
		public void Set(int i, int v){
			if (i < 2){
				indexes[i] = v;
				return;
			}
			AIDebug.Warning("AIPick index out of range");
			return;
		}
	}
}

