//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AIMemory
{
	public class TimeValues
	{
		private List<float> values = new List<float>();
		public float Sum;
		
		public void Clear(){
			values.Clear();
			Sum = 0;
		}
		
		public void Add(float v){
			values.Add(v);
			Sum += v;
		}
		
		public float Average{
			get{return (Sum / values.Count);}
		}
		
		public int Count{
			get{return  values.Count;}
		}
	}
}

